import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import CurrentWeather from '../components/CurrentWeather';
import WeatherDataProvider from '../context/WeatherDataContext';
import { getWeather, WeatherData } from './api/getCurrentWeather';

const Home: NextPage<{ data: WeatherData }> = ({ data }) => {
    return (
        <div>
            <Head>
                <title>Weather App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link
                    rel="preconnect"
                    href="https://fonts.gstatic.com"
                    crossOrigin="anonymous"
                />
                <link
                    href="https://fonts.googleapis.com/css2?family=Raleway:wght@100;500;600;700&display=swap"
                    rel="stylesheet"
                ></link>
                <link
                    href="https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css"
                    rel="stylesheet"
                />
            </Head>

            <main>
                <WeatherDataProvider data={data}>
                    <CurrentWeather />
                </WeatherDataProvider>
            </main>
        </div>
    );
};

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
    // navigator.geolocation.getCurrentPosition(function (position) {
    //     console.log(position);
    // });
    const ip = req.headers['x-real-ip'] || req.connection.remoteAddress;
    console.log('IP: ', ip);
    const resp = await getWeather({ ip });
    return {
        props: {
            data: resp,
        },
    };
};

export default Home;
